/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    locations: Location;
    reviews: Review;
    faqs: Faq;
    'gallery-items': GalleryItem;
    'main-page-headlines': MainPageHeadline;
    offers: Offer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    'main-page-headlines': MainPageHeadlinesSelect<false> | MainPageHeadlinesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The people who can log in and edit this website’s content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every photo and video used on the website lives here. Upload once, then pick it wherever you need it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A short description of what’s in the photo, for example "Technician installing a tankless water heater". This helps Google find your site and helps visitors using screen readers.
   */
  alt: string;
  /**
   * Optional note for your own reference.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The plumbing services shown on the Our Services page, the home page showcase, and each service’s own detail page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * For example "Water Heaters" or "Drain & Sewer".
   */
  title: string;
  /**
   * Keeps existing links to this service working. Please don’t change this without checking with your web developer.
   */
  anchorId: string;
  /**
   * One or two sentences shown on this service’s card.
   */
  blurb: string;
  /**
   * Short selling points listed under the description, for example "Same-day service".
   */
  bullets: {
    text: string;
    id?: string | null;
  }[];
  /**
   * The highlight color used on this service’s card.
   */
  accent: 'blue' | 'red';
  /**
   * Check this to feature this service in the big showcase on the home page.
   */
  featured?: boolean | null;
  /**
   * A short, punchy name for the home page showcase, for example "Drains & Sewer". If left blank, the service name is used.
   */
  showcaseTitle?: string | null;
  /**
   * A small label shown on the showcase image, for example "Most popular".
   */
  showcaseBadge?: string | null;
  /**
   * The photo shown for this service in the home page showcase.
   */
  showcaseImage?: (number | null) | Media;
  /**
   * The photo shown on this service’s own page.
   */
  detailImage?: (number | null) | Media;
  /**
   * The last part of this page’s address, for example "water-heaters" makes the page yoursite.com/services/water-heaters. Use lowercase letters and dashes.
   */
  slug?: string | null;
  /**
   * The big first line at the top of the page, for example "Hot water, without the drama."
   */
  heroHeadline?: string | null;
  /**
   * Problems a homeowner might recognize, for example "Hot water runs out faster than it used to".
   */
  signs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The steps of the job, in order, for example "1. We inspect" → "2. We quote".
   */
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Big number + short caption pairs, for example "4000 PSI" with "Hydro-jetting scours pipes to like-new".
   */
  stats?:
    | {
        /**
         * For example "4000 PSI" or "24/7".
         */
        value: string;
        /**
         * What the number means.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Questions and answers specific to this service.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Services with lower numbers appear first on the website.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The city pages on the website — one page for each area you serve.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * For example "Sarasota" or "North Port".
   */
  city: string;
  /**
   * The last part of this page’s address, for example "north-port" makes the page yoursite.com/locations/north-port. Use lowercase letters and dashes, and avoid changing it once the page is live.
   */
  slug: string;
  /**
   * For example "Sarasota" — no need to include the word "County".
   */
  county: string;
  /**
   * The welcome paragraph at the top of this city’s page.
   */
  intro: string;
  /**
   * Neighborhoods or communities near this city that you also serve.
   */
  nearby: {
    area: string;
    id?: string | null;
  }[];
  /**
   * The one-or-two-sentence summary Google may show under this page in search results. Mention the city and your key services.
   */
  metaDescription: string;
  /**
   * The large photo at the top of this city’s page.
   */
  heroImage?: (number | null) | Media;
  /**
   * Cities with lower numbers appear first on the website.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews shown on the Reviews page and the home page. Tip: also update the overall rating numbers under Site Settings → Review Rating.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * For example "Mike R." — first name and last initial is a nice touch.
   */
  name: string;
  /**
   * From 1 to 5 stars.
   */
  rating: number;
  /**
   * The customer’s words. Feel free to trim long reviews to the best part.
   */
  text: string;
  /**
   * Shown under the name, for example "Sarasota, FL". Optional.
   */
  location?: string | null;
  /**
   * For example "Water heater install". Optional.
   */
  service?: string | null;
  /**
   * For example "Google Reviews" or "Facebook".
   */
  source?: string | null;
  /**
   * Shown with the review, in any format you like — for example "March 2026". Optional.
   */
  date?: string | null;
  /**
   * Uncheck to hide this review from the website without deleting it.
   */
  published?: boolean | null;
  /**
   * Reviews with lower numbers appear first on the website.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * General questions and answers shown on the website. For questions about one specific service, edit that service instead — each service has its own "Common questions" section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Written the way a customer would ask it, for example "Do you offer free estimates?"
   */
  question: string;
  /**
   * Keep it friendly and to the point — a few sentences is plenty.
   */
  answer: string;
  /**
   * Questions with lower numbers appear first on the website.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The photos shown in the Gallery page grid — great for before-and-afters and finished jobs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  /**
   * A short caption shown with the photo, for example "Tankless water heater install".
   */
  label: string;
  image: number | Media;
  /**
   * Check this for portrait-shaped photos — they get a taller spot in the gallery grid.
   */
  tall?: boolean | null;
  /**
   * Uncheck to hide this photo from the gallery without deleting it.
   */
  published?: boolean | null;
  /**
   * Photos with lower numbers appear first in the gallery.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The heading at the top of each main page — the small label, the big headline, and the sentence under it. Add one entry per page; pages without an entry keep their built-in wording.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-page-headlines".
 */
export interface MainPageHeadline {
  id: number;
  /**
   * The page this headline appears on. Each page can only have one entry.
   */
  page: 'our-services' | 'about-us' | 'reviews' | 'contact' | 'gallery';
  /**
   * The short red label above the headline, for example "About us".
   */
  eyebrow: string;
  /**
   * The big heading at the top of the page, for example "A family owned plumbing company that cares."
   */
  title: string;
  /**
   * The sentence shown under the headline, for example "Built on trust, quality, and 20+ years of experience in the area." Leave empty to show nothing.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The deals shown in the "Current offers & savings" section of the About Us page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  /**
   * The headline of the deal, for example "$75 Off Any Water Heater Install".
   */
  title: string;
  /**
   * A sentence explaining the offer, for example "Tank or tankless — mention this offer when you book."
   */
  detail: string;
  /**
   * The small text at the bottom of the card, for example "One per household. Cannot combine with other offers."
   */
  fine?: string | null;
  /**
   * Uncheck to take this offer off the website without deleting it.
   */
  published?: boolean | null;
  /**
   * Offers with lower numbers appear first on the website.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'main-page-headlines';
        value: number | MainPageHeadline;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  anchorId?: T;
  blurb?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  accent?: T;
  featured?: T;
  showcaseTitle?: T;
  showcaseBadge?: T;
  showcaseImage?: T;
  detailImage?: T;
  slug?: T;
  heroHeadline?: T;
  signs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  city?: T;
  slug?: T;
  county?: T;
  intro?: T;
  nearby?:
    | T
    | {
        area?: T;
        id?: T;
      };
  metaDescription?: T;
  heroImage?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  rating?: T;
  text?: T;
  location?: T;
  service?: T;
  source?: T;
  date?: T;
  published?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  label?: T;
  image?: T;
  tall?: T;
  published?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-page-headlines_select".
 */
export interface MainPageHeadlinesSelect<T extends boolean = true> {
  page?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  detail?: T;
  fine?: T;
  published?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Business info, contact details, and site-wide photos. Changes here show up across the whole website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The full business name, for example "H2O Pros Plumbing".
   */
  name: string;
  /**
   * A shorter version used where space is tight, for example "H2O Pros".
   */
  shortName: string;
  /**
   * A short slogan shown alongside the business name.
   */
  tagline?: string | null;
  /**
   * Shown on the website exactly as typed, for example "(941) 555-0123". The click-to-call link is created automatically.
   */
  phone: string;
  phoneHref: string;
  /**
   * Where website visitors can email you. The email link is created automatically.
   */
  email: string;
  emailHref: string;
  /**
   * Shown in the website footer, for example "CFC1428968".
   */
  license: string;
  /**
   * A short phrase describing where you work, for example "Sarasota & Manatee Counties".
   */
  serviceArea: string;
  /**
   * One or two sentences about the business. Used in the footer and shown to search engines like Google.
   */
  description: string;
  /**
   * The main logo, shown in the header and on the home page.
   */
  logo?: (number | null) | Media;
  /**
   * The links in the menu at the top of every page. Drag to reorder.
   */
  nav: {
    /**
     * What the link says, for example "Our Services".
     */
    label: string;
    /**
     * The page the link goes to, for example "/our-services".
     */
    href: string;
    id?: string | null;
  }[];
  /**
   * Each row is one line of the hours list, for example "Mon–Fri" and "8am – 6pm".
   */
  hours: {
    /**
     * For example "Mon–Fri" or "Emergencies".
     */
    label: string;
    /**
     * For example "8am – 6pm" or "24/7".
     */
    value: string;
    id?: string | null;
  }[];
  /**
   * The counties listed on the website, for example "Sarasota County".
   */
  counties: {
    name: string;
    id?: string | null;
  }[];
  /**
   * Shown next to the stars across the site, for example "5.0".
   */
  ratingAverage: string;
  /**
   * The total review count, for example 127. Update this as new reviews come in.
   */
  ratingCount: number;
  /**
   * For example "Google Reviews".
   */
  ratingSource: string;
  /**
   * Links to your social media pages, shown in the footer.
   */
  socials?:
    | {
        /**
         * For example "Facebook" or "Instagram".
         */
        label: string;
        /**
         * The full web address, for example "https://facebook.com/h2opros".
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Not visible on the page — read by Google and screen readers. For example "We are your friendly, neighborhood plumbing experts".
   */
  homeHeroHeadline?: string | null;
  /**
   * For example "Friendly plumbers."
   */
  homeHeroLeftLine1?: string | null;
  /**
   * For example "Honest pricing."
   */
  homeHeroLeftLine2?: string | null;
  /**
   * For example "Quality workmanship."
   */
  homeHeroRightLine1?: string | null;
  /**
   * For example "Proven results."
   */
  homeHeroRightLine2?: string | null;
  /**
   * The service names that scroll across the bottom of the hero, for example "Water Heaters". Drag to reorder.
   */
  homeHeroTicker?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The video that plays behind the home page hero. MP4 format works best; keep it under ~10 MB so the page loads fast.
   */
  homeHeroVideo?: (number | null) | Media;
  /**
   * The smaller, tilted photo on the left.
   */
  homeHeroCardLeft?: (number | null) | Media;
  /**
   * The large photo in the middle.
   */
  homeHeroCardCenter?: (number | null) | Media;
  /**
   * The smaller, tilted photo on the right.
   */
  homeHeroCardRight?: (number | null) | Media;
  /**
   * Shown on the About Us page.
   */
  teamPhoto?: (number | null) | Media;
  /**
   * The map image showing your coverage area.
   */
  serviceAreaMap?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  tagline?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  emailHref?: T;
  license?: T;
  serviceArea?: T;
  description?: T;
  logo?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  hours?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  counties?:
    | T
    | {
        name?: T;
        id?: T;
      };
  ratingAverage?: T;
  ratingCount?: T;
  ratingSource?: T;
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  homeHeroHeadline?: T;
  homeHeroLeftLine1?: T;
  homeHeroLeftLine2?: T;
  homeHeroRightLine1?: T;
  homeHeroRightLine2?: T;
  homeHeroTicker?:
    | T
    | {
        text?: T;
        id?: T;
      };
  homeHeroVideo?: T;
  homeHeroCardLeft?: T;
  homeHeroCardCenter?: T;
  homeHeroCardRight?: T;
  teamPhoto?: T;
  serviceAreaMap?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}